using Locale.Models;
using System.Text;

namespace Locale.Formats;

/// <summary>
/// Handler for PO/Gettext localization files.
/// </summary>
public sealed partial class PoLocalizationFormat : LocalizationFormatBase
{
    /// <inheritdoc />
    public override string FormatId => "po";

    /// <inheritdoc />
    public override IReadOnlyList<string> SupportedExtensions => [".po"];

    /// <inheritdoc />
    public override LocalizationFile Parse(Stream stream, string? filePath = null)
    {
        using StreamReader reader = new(stream);
        string content = reader.ReadToEnd();
        List<LocalizationEntry> entries = [];

        // Simple line-by-line parsing
        string[] lines = content.Split('\n');
        string? currentMsgid = null;
        string? currentMsgstr = null;
        string? currentComment = null;
        bool inMsgid = false;
        bool inMsgstr = false;

        foreach (string rawLine in lines)
        {
            string line = rawLine.TrimEnd('\r');

            // Handle comments
            if (line.StartsWith("#. "))
            {
                currentComment = line[3..];
                continue;
            }

            // Skip other comments
            if (line.StartsWith('#'))
            {
                continue;
            }

            // Handle msgid
            if (line.StartsWith("msgid "))
            {
                // Save previous entry
                if (currentMsgid != null && currentMsgstr != null && !string.IsNullOrEmpty(currentMsgid))
                {
                    entries.Add(new LocalizationEntry
                    {
                        Key = currentMsgid,
                        Value = currentMsgstr,
                        Comment = currentComment
                    });
                }

                const int MsgidPrefixLength = 6; // "msgid ".Length
                currentMsgid = ExtractQuotedString(line[MsgidPrefixLength..]);
                currentMsgstr = null;
                currentComment = null;
                inMsgid = true;
                inMsgstr = false;
                continue;
            }

            // Handle msgstr
            if (line.StartsWith("msgstr "))
            {
                const int MsgstrPrefixLength = 7; // "msgstr ".Length
                currentMsgstr = ExtractQuotedString(line[MsgstrPrefixLength..]);
                inMsgid = false;
                inMsgstr = true;
                continue;
            }

            // Handle continuation lines
            if (line.StartsWith('"') && line.EndsWith('"'))
            {
                string value = ExtractQuotedString(line);
                if (inMsgid && currentMsgid != null)
                {
                    currentMsgid += value;
                }
                else if (inMsgstr && currentMsgstr != null)
                {
                    currentMsgstr += value;
                }
            }
        }

        // Add last entry
        if (currentMsgid != null && currentMsgstr != null && !string.IsNullOrEmpty(currentMsgid))
        {
            entries.Add(new LocalizationEntry
            {
                Key = currentMsgid,
                Value = currentMsgstr,
                Comment = currentComment
            });
        }

        return new LocalizationFile
        {
            FilePath = filePath ?? "",
            Culture = DetectCultureFromFileName(filePath),
            Format = FormatId,
            Entries = entries
        };
    }

    private static string ExtractQuotedString(string value)
    {
        value = value.Trim();
        if (value.StartsWith('"') && value.EndsWith('"'))
        {
            value = value[1..^1];
        }

        // Unescape
        return value
            .Replace("\\n", "\n")
            .Replace("\\r", "\r")
            .Replace("\\t", "\t")
            .Replace("\\\"", "\"")
            .Replace("\\\\", "\\");
    }

    /// <inheritdoc />
    public override void Write(LocalizationFile file, Stream stream)
    {
        using StreamWriter writer = new(stream, Encoding.UTF8, leaveOpen: true);

        // Write header
        writer.WriteLine("# PO file generated by Locale");
        writer.WriteLine("msgid \"\"");
        writer.WriteLine("msgstr \"\"");
        writer.WriteLine("\"Content-Type: text/plain; charset=UTF-8\\n\"");
        writer.WriteLine("\"Content-Transfer-Encoding: 8bit\\n\"");
        writer.WriteLine();

        foreach (LocalizationEntry entry in file.Entries)
        {
            if (!string.IsNullOrEmpty(entry.Comment))
            {
                writer.WriteLine($"#. {entry.Comment}");
            }

            writer.WriteLine($"msgid {QuotePo(entry.Key)}");
            writer.WriteLine($"msgstr {QuotePo(entry.Value ?? "")}");
            writer.WriteLine();
        }
    }

    private static string QuotePo(string value)
    {
        string escaped = value
            .Replace("\\", "\\\\")
            .Replace("\"", "\\\"")
            .Replace("\n", "\\n")
            .Replace("\r", "\\r")
            .Replace("\t", "\\t");
        return $"\"{escaped}\"";
    }
}