using Locale.Models;
using System.Text;
using System.Text.RegularExpressions;

namespace Locale.Formats;

/// <summary>
/// Handler for Visual Basic resource wrapper files (.vb).
/// Provides best-effort read-only support for extracting key/value data from
/// strongly-typed VB resource wrapper files.
/// 
/// Note: Direct parsing of .vb files is inherently ambiguous. When possible,
/// prefer using the underlying .resx files as the authoritative source.
/// This format is provided for inspection purposes and may not capture all resources.
/// </summary>
public sealed partial class VbResourceLocalizationFormat : LocalizationFormatBase
{
    /// <inheritdoc />
    public override string FormatId => "vb";

    /// <inheritdoc />
    public override IReadOnlyList<string> SupportedExtensions => [".vb"];

    /// <inheritdoc />
    public override LocalizationFile Parse(Stream stream, string? filePath = null)
    {
        using StreamReader reader = new(stream);
        string content = reader.ReadToEnd();
        List<LocalizationEntry> entries = [];

        // Look for property patterns that return string resources
        // Common patterns:
        // Public ReadOnly Property Hello() As String
        //     Get
        //         Return ResourceManager.GetString("Hello", resourceCulture)
        //     End Get
        // End Property

        Regex propertyPattern = PropertyPatternRegex();
        MatchCollection matches = propertyPattern.Matches(content);

        foreach (Match match in matches)
        {
            string propertyName = match.Groups[1].Value;
            string resourceKey = match.Groups[2].Value;

            // Use the resource key as the key
            entries.Add(new LocalizationEntry
            {
                Key = resourceKey,
                Value = null, // Value is in the .resx file, not in .vb wrapper
                Comment = $"Property: {propertyName}"
            });
        }

        // Also try to find simple string constants
        Regex constPattern = ConstPatternRegex();
        MatchCollection constMatches = constPattern.Matches(content);

        foreach (Match match in constMatches)
        {
            string constName = match.Groups[1].Value;
            string constValue = match.Groups[2].Value;

            // Unescape VB string
            constValue = constValue.Replace("\"\"", "\"");

            entries.Add(new LocalizationEntry
            {
                Key = constName,
                Value = constValue
            });
        }

        return new LocalizationFile
        {
            FilePath = filePath ?? "",
            Culture = DetectCultureFromFileName(filePath),
            Format = FormatId,
            Entries = entries
        };
    }

    /// <inheritdoc />
    public override void Write(LocalizationFile file, Stream stream)
    {
        // VB resource files are typically auto-generated and should not be
        // modified directly. Instead, modify the source .resx file.
        using StreamWriter writer = new(stream, Encoding.UTF8, leaveOpen: true);

        writer.WriteLine("' ===============================================================================");
        writer.WriteLine("' WARNING: This file is auto-generated by Locale for inspection purposes only.");
        writer.WriteLine("' Do not edit this file directly. Modify the source .resx file instead.");
        writer.WriteLine("' ===============================================================================");
        writer.WriteLine();
        writer.WriteLine("Imports System");
        writer.WriteLine("Imports System.Resources");
        writer.WriteLine();
        writer.WriteLine("Namespace My.Resources");
        writer.WriteLine();
        writer.WriteLine("    Friend Module Resources");
        writer.WriteLine();

        foreach (LocalizationEntry entry in file.Entries)
        {
            string safeKey = MakeSafeIdentifier(entry.Key);

            if (!string.IsNullOrEmpty(entry.Comment))
            {
                writer.WriteLine($"        ' {entry.Comment}");
            }

            if (entry.Value != null)
            {
                // Write as constant
                string escapedValue = entry.Value.Replace("\"", "\"\"");
                writer.WriteLine($"        Friend Const {safeKey} As String = \"{escapedValue}\"");
            }
            else
            {
                // Write as property that would reference ResourceManager
                writer.WriteLine($"        ' Property: {safeKey}");
                writer.WriteLine($"        ' ResourceManager.GetString(\"{entry.Key}\", resourceCulture)");
            }
            writer.WriteLine();
        }

        writer.WriteLine("    End Module");
        writer.WriteLine();
        writer.WriteLine("End Namespace");
    }

    /// <summary>
    /// Converts a key to a valid VB identifier.
    /// </summary>
    private static string MakeSafeIdentifier(string key)
    {
        // Replace dots and invalid chars with underscores
        StringBuilder result = new();

        foreach (char c in key)
        {
            if (char.IsLetterOrDigit(c) || c == '_')
            {
                result.Append(c);
            }
            else
            {
                result.Append('_');
            }
        }

        // Ensure it starts with a letter or underscore
        if (result.Length > 0 && char.IsDigit(result[0]))
        {
            result.Insert(0, '_');
        }

        return result.ToString();
    }

    // Matches: Public ReadOnly Property PropertyName() As String ... GetString("ResourceKey", ...)
    [GeneratedRegex(@"Public\s+(?:Shared\s+)?ReadOnly\s+Property\s+(\w+)\s*\(\s*\)\s+As\s+String[\s\S]*?GetString\s*\(\s*""([^""]+)""\s*,", RegexOptions.IgnoreCase)]
    private static partial Regex PropertyPatternRegex();

    // Matches: Const ConstName As String = "Value"
    [GeneratedRegex(@"(?:Public|Friend|Private)?\s*Const\s+(\w+)\s+As\s+String\s*=\s*""([^""]*(?:""""[^""]*)*)""", RegexOptions.IgnoreCase)]
    private static partial Regex ConstPatternRegex();
}